version: "3.9"
services:
  db:
    image: postgres:13.3-alpine
    container_name: diploma-db-container
    ports:
      - "5444:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: diploma
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always

  app:
    image: staffsterr2000/diploma-app:1.0.0
    container_name: diploma-app-container
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_HOST: db
      DATASOURCE_PORT: 5432
      DATASOURCE_DB: diploma
    restart: always
    links:
      - db

#  mail:
#    image: maildev/maildev
#    container_name: diploma-mail-container
#    command: bin/maildev -w 1080 -s 1025
#    ports:
#      - "1025:25"
#      - "1080:1080"