version: "3.9"
services:
  db:
    image: postgres:13.3-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 258456
      POSTGRES_USER: postgres
      POSTGRES_DB: diploma
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    build: .
    container_name: application
    ports:
      - "8080:8080"
    environment:
      APPLICATION_HOST: app
      MAILDEV_HOST: mail
      POSTGRES_HOST: db
      POSTGRES_DB: diploma
    restart: always
    links:
      - db
  mail:
    image: maildev/maildev
    container_name: maildev
    command: bin/maildev -w 1080 -s 1025
    ports:
      - "1025:25"
      - "1080:1080"
