--INSERT INTO application_user (id, role, image_link, username, email, password, is_account_locked, is_enabled)
--    VALUES (1, 'CLIENT', 'default.jpg', 'roshchenko_stas', 'roshchenko_stas@gmail.com', 'password', FALSE, TRUE);
--
--INSERT INTO application_user (id, role, image_link, username, email, password, is_account_locked, is_enabled)
--    VALUES
--        (2, 'DOCTOR', 'lobanov_semen.jpg', 'lobanov_semen', 'lobanov_semen@gmail.com', 'password', FALSE, TRUE),
--        (3, 'DOCTOR', 'chernous_varvara.jpg', 'varya69', 'varya69@gmail.com', 'password', FALSE, TRUE),
--        (4, 'DOCTOR', 'richards_phil.jpg', 'american_boy', 'uedu_s_toboy@gmail.com', 'password', FALSE, TRUE),
--        (5, 'DOCTOR', 'bikov_andrey.jpg', 'bikov_v_kedah', 'bikov@gmail.com', 'password', FALSE, TRUE),
--        (6, 'DOCTOR', 'levin_boris.jpg', 'levin_v_kedah', 'levin_borya@gmail.com', 'password', FALSE, TRUE),
--        (7, 'DOCTOR', 'kupitman_ivan.jpg', 'kupi_dom', 'kupitman_vanya@gmail.com', 'password', FALSE, TRUE),
--        (8, 'DOCTOR', 'romanenko_gleb.jpg', 'gleb_roma', 'glebgleb@gmail.com', 'password', FALSE, TRUE);
--
--SELECT setval('application_user_id_seq', 9);